CREATE DATABASE IF NOT EXISTS quanly_noidung;

USE quanly_noidung;

CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLES ENUM('admin', 'editor', 'author') NOT NULL
);

CREATE TABLE CATEGORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIBES VARCHAR(255) , 
    NOTE VARCHAR(255)
);


CREATE TABLE ARTICLE (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    ARTICLENAME VARCHAR(255) NOT NULL UNIQUE, 
    CATEGORYID INT NOT NULL, 
    ARTICLESUM VARCHAR(255), 
    CONTENT TEXT,
    NOTE VARCHAR(255), 
    DAYCREATE VARCHAR(50) NOT NULL, 
    DAYMODIFIED VARCHAR(50) ,
    AUTHORID INT NOT NULL,
    FOREIGN KEY (AUTHORID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY(ID)

);



-- Create sample data
-- admin password is 'ltatweb@123'
INSERT INTO USERS (USERNAME, PASSWORD_HASH, ROLES) VALUES 
('admin', 'ltatweb@123', 'admin'),
('author', 'ltatweb@123', 'author');

-- Insert sample data to CATEGORY table
INSERT INTO CATEGORY (DESCRIBES, NOTE) VALUES
('TN1', 'TN1 description'),
('TN2', 'NCC 2 description');

-- Insert sample data to products table
INSERT INTO ARTICLE (ARTICLENAME, CATEGORYID, ARTICLESUM, CONTENT, DAYCREATE, AUTHORID) VALUES
('ARTICLE 1', 1, 'ARTICLE 1 Sumary','ARTICLE 1 CONTENT',CURRENT_DATE(), 1),
('ARTICLE 2', 2, 'ARTICLE 2 Sumary','ARTICLE 2 CONTENT',CURRENT_DATE(), 2),
('ARTICLE 3', 1, 'ARTICLE 3 Sumary','ARTICLE 3 CONTENT',CURRENT_DATE(), 1);







