version: '3.8'

services:
  apache_php:
    image: myphp:8.1-apache
    container_name: apache_php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: secure_article_management
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306" 
    volumes:
#      - ./db/mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
